### ISSUE TITLE
Automatic Downloading?

### ISSUE THREAD

**Issue by racingPeter** [Lewdninja/liveme-pro-tools#103]
Is there a way to automatically download live sessions when a selected user begins streaming? If not, are there other tools that let you do this?

**Comment by tp9ine** [comment]
Yes. LAMD. Not sure if it still works though or it needs an update. I have no idea how to set it up.

**Comment by tp9ine** [comment]
It's in Lewdninja's repositories. You have to download the files. I don't know anything other than that.

**Comment by Xqqz** [comment]
@racingPeter  ,  No longer works: 
issue: https://github.com/Lewdninja/lamd/issues/1

I was going to request this feature be added to LMPT . (intergrate LAMD into LMPT)

Feature: 
LMPT users would be able to select 1, or any, or ALL Bookmarked Liveme broadcasters ID to have their replays AUTO DOWNLOAD. 

LAMD in LMPT could be set to scan Bookmarks every 5 or 15 or 30 minutes etc., if it detects a Bookmarked user is LIVE, it would SAVE all the broadcast URL PATH  and SOURCE PATH in an .INI or .json  file ( because sometimes Broadcasters delete the broadcast ) 

When the Live  has ENDED, LMPT with LAMD would SCAN the .ini/.json file and AUTOMATICALLY DOWNLOAD the REPLAY ( if that users ID is selected  for AUTO DOWNLOADS ).

If a broadcaster deleted the replay , the URL and SOURCE will remain in the .ini/.json file, marked with [DELETED] in the line of that deleted Replays' url/source.

**Comment by ddpk** [comment]
@Xqqz What are the "url path" and "source path" meaning? You want it to save the videoID url right? But if it's saving the source path when it detects a LIVE broadcast, that won't be the replay m3u8, right? You could however make it grab and save the replay source m3u8 timed perfectly after the broadcast ends, since all myqcloud replays generate at exactly the same time no matter how long the broadcast was (10:00 minutes) 

Although saving the URL is helpful, but it could also just save the URL as the filename. I had many ideas about this before I knew LAMD was a thing. I guess since it wasn't usable I never heard about it. Here they are if you wanna read them and didnt see https://github.com/Lewdninja/liveme-pro-tools/issues/20

**Comment by Xqqz** [comment]
@ddpk 

![bandicam 2018-06-02 21-50-19-366](https://user-images.githubusercontent.com/38635388/40882418-e15e3f78-66d0-11e8-8aa7-724401d27a09.jpg)


https://www.liveme.com/live.html?videoid=12345678987654321 <<=URL
http://1253467418.vod2.myqcloud.com/4683c5bbvodca1253467418/e6c8c44d755872366146051217/playlist_eof.m3u8 <<=Source

If LMPT detects it as a LIVE stream... save the URL/SOURCE in the ini/json file until next  SCAN ( .ini/.json etc ) ., along with all new REPLAYS

at intervals LMPT/LAMD would SCAN the list and download all FINISHED Broadcast ( of selected Broadcaster(s) set for AUTO-DOWNLOAD )

the ini/json file would look like [success] << indicates downloaded

https://www.liveme.com/live.html?videoid=12345678987654321 [success]
http://1253467418.vod2.myqcloud.com/4683c5bbvodca1253467418/e8jhc44d7558726785605174/playlist_eof.m3u8 [success]

https://www.liveme.com/live.html?videoid=777178987654321 [success]
http://1253467418.vod2.myqcloud.com/4683c5bbvodca1253467418/e6c8c44d755872366146051217/playlist_eof.m3u8 [success]

Broadcasts that was DELETED before DOWNLOADING would list as NOT FOUND/DELETED/FAILED , etc.

https://www.liveme.com/live.html?videoid=6666668987654321 [NOT FOUND]
http://1253467418.vod2.myqcloud.com/4683c5bbvodca555553467418/e6c8c5252146051217/playlist_eof.m3u8 [NOT FOUND]

* some deleted broadcasts are still available for viewing thru Liveme.com , and by download managers apps. using the SOURCE. for a period of time.
