### ISSUE TITLE
Failed to autenticate

### ISSUE THREAD

**Issue by bootyislife** [Lewdninja/liveme-pro-tools#119]
Like it's getting quite annoying have to play the damn waiting game when it fails to authenticate. Like can we just please have a fix for this already, saw others were saying it helps to reset settings. It's annoying enough as is that I have to set ffmpeg path every other time I open it. We are literally fucked if we ever close the program because we won't be able to authenticate.

**Comment by izmore** [comment]
can we please get rid of the authentication....nothing but problems since day 1 and no fix for months.

**Comment by scozz76** [comment]
Maybe it's not the software. I noted on another post yesterday that all I had to do was change my VPN location for it to function properly. It did take a little bit of searching to find a location that worked, this is why I feel it may not be software related.

If you are having problems with losing your FFMPEG location settings all you have to do is follow the instructions on the download page regarding FFMPEG location and add the path to windows (environment variables)

If you don't like the "FREE" software, you are welcome to write your own.

**Comment by bootyislife** [comment]
@scozz76 "If you are having problems with losing your FFMPEG location settings all you have to do is follow the instructions on the download page regarding FFMPEG location and add the path to windows (environment variables)"

I manually set my ffmpeg location because it even being in C: and have enviroment variables it still sometimes fucks up and can't find it.

"If you don't like the "FREE" software, you are welcome to write your own."
Sorry this is a github to post about issues with the software, if you are emotional about the internet then you should stay off.

**Comment by bootyislife** [comment]
But yeah, I have done everything that was marked as a "fix" for this. I removed settings, restarted fresh etc. The account is perfectly fucking fine because I logged into it on mobile and browser (A DAY AGO). Literally the only way for this authentication to not pop up is to basically never close it.

**Comment by Xqqz** [comment]
Is this really a LMPT issue ... or a LiveMe.com issue ?

What's the link to the Discord chat ?

**Comment by greatsalmonrun** [comment]
This is more than likely a LiveMe issue, they're probably refusing connections based on certain criteria.

**Comment by hunter759** [comment]
Looks like it could be an issue. I tried all the usual steps. I clear the cache, i reinstalled, tried a second account. Nothing will authenticate. I also tried running a vpn to switch my ip and no luck there either. I did  see that he has done some work in the liveme api, could be a fix coming.

**Comment by Xqqz** [comment]
@bootyislife  , are you a damn idiot ?? or you just play one all the time ?


let me ask you a hypothetical question.

1: If the LMPT APP version 1.1.9 has been working perfectly for WEEKS for  everyone, and
2: Nobody has UPDATED their copy of the APP from 1.1.9, and
3: Everyone  suddenly received the SAME "authentication error" at (basically) the same day/time, 

Shouldn't "COMMON SENSE" tell YOU that maybe, just MAYBE, the problem is with the Liveme server, or Live me made changes to their API ? (since a perfectly running (LMPT) APP did NOT make ANY CHANGES/updates to its core ) ?

Think about THAT for a while, you are free to "seek assistance" if you are unable to do logical deductions on your own.

You said " Sorry this is a github to post about issues with the software, if you are emotional about the internet then you should stay off."

DA, this is NOT an issue with the software, too difficult to fathom that on your own ? ....
If you are too emotional to deal with LMPT then YOU should write your own script, and maybe YOU should stay off the internet... JS

**Comment by Xqqz** [comment]
@izmore  "can we please get rid of the authentication"

Do you even understand what you just wrote ?

on second thought,  who is this "we" that you are referring to ?

**Comment by scozz76** [comment]
@bootyislife The FFMPEG directory should be in C:\Windows (and add the path in windows) to avoid the issue of FFMPEG not working after you go into LMPT settings.

**Comment by miketiger714** [comment]
scozz76 is right about the VPN. Liveme is seemingly refusing to authenticate from certain locations. So far, I am able to login using Mexico and UK VPNs. Canada and the US servers seemed to be mostly blocked.

**Comment by hunter759** [comment]
Did not have the same results here, i tried multiple locations through vpn and no success. Of course UK and Mexico as you listed, but others as well and no luck for me. Thanks for the tip though, might work fro somebody.

**Comment by bootyislife** [comment]
@Xqqz Just looked at the first part of what you said and it looked so irrelevant that I didn't even bother reading rest. Fuck out of here child.
