### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by Johnlourence** [Lewdninja/liveme-pro-tools#147]
All my bookmarks are gone. I have not deleted them, how do I retrieve.

**Comment by Xqqz** [comment]
@Johnlourence 
If you did NOT or do not have a backup of bookmark.json , then you are out of luck

suggestion: always backup your bookmark.json when you exit LMPT ( like everyday ) 

also, if LMPT shows pop-up ERRORS when you are STARTING IT... DO NOT CLOSE LMPT.... but  iMMEDIATELY go into Userdata/Roaming/Live-Me-Pro-Tools folder and back up ALL files
because SOMETIMES when LMPT crashes, it deletes/resets all those files in the UserData LMPT folder....

**Comment by Xqqz** [comment]
also

You should be getting latest RELEASES from

https://github.com/thecoder75/liveme-pro-tools/releases

https://github.com/thecoder75/liveme-pro-tools/issues
