### ISSUE TITLE
Forever queue'd downloads

### ISSUE THREAD

**Issue by m4gnet98** [Lewdninja/liveme-pro-tools#2]
Hi Lewdninja. I really appreciate you taking this up if Thecoder is leaving.

However, as you might have noticed over at https://github.com/thecoder75/liveme-pro-tools/issues/23 , something's wrong. Clicking the Download button adds the replay to the queue, but it stays there.
Example: https://my.mixtape.moe/aoauke.png

Thanks none the less, if not Thecoder, hope you can fix it mate.

cheers

**Comment by Lewdninja** [comment]
Looking into it, couldn't reproduce before.. now seems to affect me as well.

**Comment by mmind99** [comment]
Thanks for looking into this.  For those looking for a temp work around.  jdownloader2 works nicely.  Just have it running in the background, then when you copy the URL inside the app, jd2 picks right up on it.

**Comment by goncaloalourenco** [comment]
Hey Ninja, thank you so much for taking over the project! As a suggestion I'd like to add, and anyone tell me if they agree, the way downloads were handled on previous versions of livemetools (i.e 7.0.9), wget the chucks and then concat them into one file, worked so well and was so much faster than the tedious rip of a m3u8 stream with ffmpeg implemented on protools, which can take a lot of time for bigger replays. Any way we could roll back onto the older way of getting replays, and if not, maybe you could just kindly implement the login method to the source of the older livemetools? Thank you and best of luck!

**Comment by Lewdninja** [comment]
Why was it previously switched over to the ffmpeg method in that case?

**Comment by sodoffb** [comment]
That dude doesn't know what he's on about. FFMPEG is much better for handling the media conversion of the m3u8 files and actually prevents a lot of the little packet skips that were common in the .ts files when using the old downloader that caused misaligned timestamps, frozen video, etc. The reason why it's slow for him is probably because he's using outdated hardware. Since FFMPEG converts the file on the PC to MP4, he needs to look on his end for the issue and not blame FFMPEG. The program is used by a lot of other applications without issue, including VLC, MPC, and a lot of video conversion programs like Sony Vegas, Camtasia, Adobe Premiere, etc.

**Comment by Mush-r00m** [comment]
i Also agree FFMPEG is better, i use a batch script to download m3u8 at the moment. I personally prefer the way FFMPEG & FFPLAY were manually set up inside the GUI of version 6.3.3 worked flawlessly. Infact thats still my favorite version.

**Comment by goncaloalourenco** [comment]
@sodoffb If you had looked at the source code you would have seen the replays output as .mp4 and ffmpeg is implemented for it's concatenation and conversion, along with the necessary flag. My point was that wgetting the chucks was faster that full ffmpegging the stream, at least from past experience.

**Comment by Lewdninja** [comment]
I'm not going to touch any of the FFMPEG implementations right now. Feel free to make a new issue if you guys would like to have a discussion on which download method is better.

I expect to see actual stats etc..
