### ISSUE TITLE
Feature suggestion - Likes per Minute Run Time (new column)

### ISSUE THREAD

**Issue by simonwood1** [Lewdninja/liveme-pro-tools#27]
Number of likes by itself is only a semi-useful method of determining quality. A great feature would be a column that displays Likes per Minute of Runtime. Consider these examples:

Likes  Length   Likes/min
100     2:00        50 
300     9:00        33

In the above example, the replay with _less_ likes is the probably the better one

**Comment by Lewdninja** [comment]
I mean this should be easy to add, but it's also going to add more clutter possibly. Anyone else want this to be added?

**Comment by tp9ine** [comment]
@Lewdninja you know, I was gonna ask to add a column for broadcastid (the 15xxxxxxxxx number) somewhere, like the old LMT had. But I guess that's gonna add too much clutter too? I use LMPT on two PCs so that little blue icon that indicates whether or not you've downloaded the file before, won't be of help here.

I've been using "broadcastid - longid - broadcaster name" since the beginning of time. (broadcastid first because it contains the unix time so it keeps files in chronological order).

So yeah as it stands now there is no way to quickly tell with a glance at a replay list to see iif you have a file or not already. It's kinda annoying that it only appears when you open the video with the player.

**Comment by barakaka** [comment]
i would like the likes/minute column.  There could be settings where people choose what columns they want if it gets cluttered.

**Comment by smagdan** [comment]
Likes aren’t really a thing on liveme anymore.. don’t think it would be that meaningful. Maybe shares or diamonds per minute but 🤷🏻‍♂️

**Comment by simonwood1** [comment]
Diamonds per minute may work too, but in terms of worrying about clutter, it's not like "Title" ever contains anything meaningful ;) - so it could afford to be reduce in size. Maybe there's scope for some sort of pseudo metric like "Fun factor" which could be an algorithmic combo of Likes per Minute, Diamonds (or Diamonds per Minute) and Shares

**Comment by thegeezer9999** [comment]
Looking at the interface, title is used by many as part of the download (%%replaytitle%%), so would suggest this should be retained - it is also sometimes useful to determine the nature of the bc. I never even look at views, shares, likes, so personally speaking, if any of these were sacrificed to allow for a new (more meaningful) metric, I would be fine with that. I guess you might have a vote or poll as to which is the right metric to include - should you decide to do it :-)
