### ISSUE TITLE
help

### ISSUE THREAD

**Issue by jonty123456** [Lewdninja/liveme-pro-tools#37]
lewdninja can you please tell me how to get token back thanks

**Comment by starsaillor** [comment]
can u give us some more details abt ur problem?

**Comment by jonty123456** [comment]
cheers mate not sure how i got it in the first place downloaded pro tools and the api  i had a token on liveme but used it i thought that would get me replays but it didnt

**Comment by jonty123456** [comment]
do i need the token to see replays

**Comment by jonty123456** [comment]
thank you i will try again

**Comment by ddpk** [comment]
Don't use the same google email address that you already used to sign up to LiveMe. That won't work on LiveMeTools. Google signup email only works with Google login. Email signup only works with the Email login. The LiveMe Pro Tools provides sign in a sign in method that is not applicable to LiveMe's Google login method. It uses the Email method.

 **Email login ≠ Google login.** 
 
If you do it right, it will work. If it doesn't or you get stuck, keep trying. These are the most detailed instructions you'll get. You must follow these steps using a phone.  Otherwise you'll have to try these steps using https://downloadnox.com/

Follow these steps: 
**1. Make a valid email address that is NOT already in use for LiveMe.**
**2. Log out of existing account.**
**3. On the signup page, click "Log Into Another Account"** 
**4. Click the button circled in red here: https://i.imgur.com/Si0xL0m.png**
**5. Enter your new and valid email then click next.**
**6. Pick a random password, enter it and write it down if you might forget it.**
**7. If the "next" button on the keyboard doesn't work, click the empty white space to hide the keyboard and click next button on the screen.**
**8. Click the button to validate your email, then check your email. Click the link. Complete the captcha and click the button with chinese letters to finish.**
**9. Confirm that you validated the email in the app, then complete the profile the signup. Click skip through everything if you want.**
**10. Now log out of the mobile LiveMe app once signup is complete.** 
**11. Go to settings on LiveMe Pro Tools, enter the new Email and the password with it in the fields.**
**12. Click the X at the top right.**
**13. Enjoy the replays.**

**Comment by starsaillor** [comment]
Don't mean to bring any confusion to this, as it already seems confusing enough, but I use the very same Google account credentials on live me tools as I use in the official app, I've never used a proper email login method, always used Google instead.

**Comment by ddpk** [comment]
@starsaillor Meaning you have an account logged in with google but you also used that google account's gmail address to sign up to liveme through the other method? Or no?

**Comment by starsaillor** [comment]
Meaning that I've been using the same Google account since I started on liveme years ago, when the authentication issue rose up, I just entered my Gmail address and pass into pro tools and everything worked, I don't have an email account on live me, I always clicked the Gmail button. One detail that may be unimportant: when I enter the same credentials on the live me app, under email login, they don't work, it says I don't have an account, can't explain why tho.

**Comment by Lewdninja** [comment]
Closing this since OP hasn't answered after ddpk posted his answer, which details how to make an email account on Liveme.
