### ISSUE TITLE
Enhancement for Supporters - Ability to Rotate In-built Video Player 90degrees/180degrees/270degrees/Flip

### ISSUE THREAD

**Issue by Xqqz** [Lewdninja/liveme-pro-tools#58]
Some broadcaster sometimes turn their phones to LANDSCAPE MODE, while Live
 *even some have flipped the phone UPSIDE-DOWN ( 180 degrees ),
that makes it difficult to view on a monitor ( if you don't have options to rotate the monitor screen ) 

So, on the Inbuilt Video Player, would be nice for 2 buttons ( 1 left - 1 right ) to change Orientation of screen. 

#-1 Right-Button =  Click once to ROTATE SCREEN 90 DEGREES right , click TWICE to ROTATE SCREEN to 180 degrees ( click LEFT BUTTON to return back to normal )
#-2 Left Button = Click once to ROTATE SCREEN LEFT 90 Degrees left, click TWICE to ROTATE SCREEN to 180 DEGREES  ( Click RIGHT Button to return screen back to normal )
#-3 Flip button ( for UPSIDE-DOWN broadcasters )
![modes](https://user-images.githubusercontent.com/38635388/39805602-d4711920-5366-11e8-8f27-57883ad94b90.jpg)

# * do NOT ROTATE THE VIDEO by itself..
# ++ DO ROTATE THE player SCREEN (orientation - to landscape), the video will rotate WITH the screen.

Thanks in advance.

**Comment by rebuff10** [comment]
even if broadcaster rotates his phone video orientation is fixed for video by default in liveme policy.What are you talking about,if you add option for rotating video it can be landscape or portrait mode, which does not make sense as there is no logic of giving extra load to develop this feature on developer, when the logic for need to do it is null

**Comment by tp9ine** [comment]
yeah i kind of feel this is not really necessary. just download the video and rotate it in a media player of your choice.

**Comment by smagdan** [comment]
Just use external player. MPC can rotate by keyboard shortcut.

**Comment by smagdan** [comment]
"C:\Program Files (x86)\K-Lite Codec Pack\MPC-HC64\mpc-hc64.exe" /play /new "%url%"

**Comment by Xqqz** [comment]
@rebuff10  , you make no sense in your reply.

@tp9ine @smagdan 
So what sense  does it make then for LMPT to have a VIDEO PLAYER BUILT-IN if it cant be utilized  for when a broadcaster  rotate(s) his/her camera  during broadcast/replays ? 
Why is there a "BUILT IN PlAYER" if i "MUST download" the video (first) in order to watch it ? 

@smagdan , i already have both MPC and VLC .....  using "those" creates another "load" (opening other software)  on the computer.

**Comment by ddpk** [comment]
Lol @rebuff10 your reply hurt to try and understand. You started off by saying liveme doesn't automatically flip the video when the broadcaster rotates their phone (this isn't about that), then you repeat his idea and say it doesn't make sense because it's not logical to suggest because of it being "extra" work...   **-______-**

Every feature suggestion is work, this isn't any different than the others. This is a good idea. It seems like it'd be a simple yes or no because it'd probably be easy to add in or really hard depending on how the built in video player works..? It's better than the old one, you never know

But lewdninja seems to be taking a break with us because of constant suggestions but not many showing [interest](https://www.patreon.com/lewdninja) in supporting him while he takes on the future development and implementing new features for us. I don't blame him.

**Comment by TuxNuX** [comment]
@ddpk
the rotation in the internal player is a good idea, but on "liveme" they are rare videos 
that need rotation
and if being complicated to code @Lewdninja may not deserve to have a headache for so little video asking for rotation hahaha

**Comment by Lewdninja** [comment]
Rotating videos available to Patreon supporters: https://www.patreon.com/posts/18814760

**Comment by ddpk** [comment]
Remembering volume thing is nice, thanks for that! @Lewdninja

**Comment by Xqqz** [comment]
Thanks for adding this Enhancement

and yes, the volume-remember is a nice addition too. @Lewdninja
