### ISSUE TITLE
Request - Only the Developer should be allowed to comment on other's posts

### ISSUE THREAD

**Issue by thegeezer9999** [Lewdninja/liveme-pro-tools#59]
Too many "experts" commenting on other people's posts in here - STFU

Lewd you can close this - just making a point

**Comment by Grindteeth** [comment]
I disagree. I think some of the discussions here are quite interesting although I don't partake too much myself.

**Comment by smagdan** [comment]
The main issue is all these people overwhelming him with requests.. a lot of them pretty ridiculous.. at least contribute to his Patreon if you want him to work on all these things (only has two members).. he hasn't touched the code in over a week.

**Comment by rebuff10** [comment]
@smagdan you said right i tried the code myself to work around and i am learning it but its quite complex, i am new to JavaScript, i changed colors on ui i was able to change other things,but the complex codes like which needed something to do with yarn package,man its quite a hard work we must really contribute to developer  on patreon they are genius seriously

**Comment by Lewdninja** [comment]
I ignore the the [Experts](https://www.youtube.com/watch?v=ouyC28ffPjQ) and only look through the useful comments.

**Comment by barakaka** [comment]
> The main issue is all these people overwhelming him with requests.. a lot of them pretty ridiculous.. at least contribute to his Patreon if you want him to work on all these things (only has two members).. he hasn't touched the code in over a week.

The last 2 of these liveme toolkit things died and they barely had any discussion.  So it's not like staying quiet helps either.  At least a lot of reports tells you people are using it and appreciating it in some way.  And I used to code for a project like this and the most annoying thing would be people *not* reporting bugs or issues they have  Then you see people out in the wild complaining about some bug or missing feature and I didn't even know about it because no one reported it to me.  Also I've gotten a lot of useful info from the comments.
