### ISSUE TITLE
Internal viewer not functioning

### ISSUE THREAD

**Issue by bjps1353** [Lewdninja/liveme-pro-tools#60]
Today, the internal viewer function of the app no longer works. The remainder of the app seems to be working normally: bookmarks show up, are updated, etc. but clicking the viewing icon brings no result. Was working fine yesterday Any ideas? Thanks!

**Comment by starsaillor** [comment]
just noticed the same issue. no idea of what happened tho.

**Comment by robwas** [comment]
Same here, worked fine last night.

**Comment by starsaillor** [comment]
will try to use a custom player for the time being.

**Comment by Lewdninja** [comment]
The token doesn't work for video info, that's why the internal player doesn't work. It needs that.

**Comment by TuxNuX** [comment]
since 1 hour I have same problem
I try with MPV and VLC also do not work

I cleared all settings and cache
after new reconfiguration still impossible to read replays and lives with external drives and internal

directly open the m3u8 link with VLC or MPV good job

I have tools liveme pro linux 64 bits

for now I can not do it but later I will restart my computer and try again

**Comment by TuxNuX** [comment]
I just saw downloading of the replays also no longer working

**Comment by Lewdninja** [comment]
It will not work whatever you do. You'll have to take the "Source" link and input to your player manually until next update.

**Comment by ddpk** [comment]
Did Live.me make another small change? If so, I wonder why

**Comment by Lewdninja** [comment]
The current login method probably uses a now deprecated API. It does generate a token, but it doesn't work for acquiring video information. @ddpk

**Comment by starsaillor** [comment]
becoming a $5+ patron automatically unlocks the link right?

**Comment by Lewdninja** [comment]
@starsaillor Yup.

**Comment by ddpk** [comment]
@Lewdninja Maybe giving $5+ patrons some kind of priority or exclusiveness with sending feature ideas would help everyone? or something along those lines however you think best

**Comment by ddpk** [comment]
Damn 11 patrons in one day?

**Comment by bjps1353** [comment]
Hey. So, I contributed via Patreon, downloaded and implemented the new version (thanks LewdNinja), but now I am getting the authentication error message. I am using the same logins I used prior to this error occurring, which seemed to work fine and gave no error messages. Any ideas?

**Comment by Lewdninja** [comment]
@bjps1353 Try creating a fresh account just in case. In the meantime I'll take a look.

**Comment by TuxNuX** [comment]
@bjps1353 
maybe your authentication problem come from them

since yesterday afternoon (in France) really have a lot of bug
no notification and work again in the evening
this morning all accounts give error "Account no longer available"
replays all disappear then come back

I think that they are changing a lot of things, hope that the next update will not be obsolete just out and that @Lewdninja  again has not to go back to work for a new update
