### ISSUE TITLE
how can I or someone compile the latest version for mac?

### ISSUE THREAD

**Issue by donalddumped** [Lewdninja/liveme-pro-tools#68]
can someone guide me so I can compile it for mac? what's needed? or if someone else can do it that would be great.

**Comment by TuxNuX** [comment]
I too would like to have a "how to/tutorial" (short would be sufficient) for compile 
with
requires:
buildrequires:

if i have some time i would do a spec for build rpm

**Comment by barakaka** [comment]
i explained how to do it in the closed "mac support" thread

**Comment by beachsurfer** [comment]
What about compiling 1.1.8 for MAC.
Lot of gurus there can help us nerds... Thank you

**Comment by Lewdninja** [comment]
https://github.com/thecoder75/liveme-pro-tools/issues/13

I'm not stopping ``dmg`` files from compiling through Travis or Appveyor. Either they release or don't.
I don't have a MAC computer to debug any potential issues so it's not supported and all related issues will be closed. There's too many mac issues popping up and it's annoying since none of them are actually helpful.
