### ISSUE TITLE
1.1.8 for MAC

### ISSUE THREAD

**Issue by beachsurfer** [Lewdninja/liveme-pro-tools#72]
Hi, is there any plan to release a new version for MAC users?
Thanks

**Comment by Lewdninja** [comment]
https://github.com/thecoder75/liveme-pro-tools/issues/13

I'm not stopping ``dmg`` files from compiling through Travis or Appveyor. Either they release or don't.
I don't have a MAC computer to debug any potential issues so it's not supported and all related issues will be closed. There's too many mac issues popping up and it's annoying since none of them are actually helpful.
